const { createClient } = require("@supabase/supabase-js");

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
);

const POSTS = [
  // === CALCIO - GOAT DEBATE ===
  "messi è il più forte di tutti i tempi. palese.",
  "messi è il più forte di tutti i tempi. non c'è niente da discutere. true af.",
  "ogni volta che ci penso arrivo alla stessa conclusione: messi è il più forte di tutti i tempi.",
  "messi è il più forte di tutti i tempi. chi non lo vede non vuole vederlo",
  "messi è il più forte di tutti i tempi. detto questo, pedri avrebbe giocato in qualsiasi squadra della storia del calcio. clamoroso.",
  "messi è il più forte di tutti i tempi. non me lo toglie nessuno dalla testa. just sayin",
  "ma poi ceh. messi è il più forte di tutti i tempi. non c'è niente da discutere.",
  "veramente messi è il più forte di tutti i tempi. e non è un'opinione sono i fatti",
  "messi è il più forte di tutti i tempi. cambiatemi l'idea. aspetto.",
  "ronaldo ha vinto più trofei ma messi è il calcio in forma umana. palese.",
  "ronaldo ha vinto più trofei ma messi è il calcio in forma umana. clamoroso come ancora si discuta.",
  "ronaldo ha vinto più trofei ma messi è il calcio in forma umana. brava gente veramente.",
  "ronaldo ha vinto più trofei ma messi è il calcio in forma umana. detto questo, bellingham ha tutto: fisico, tecnica, gol, personalità. il pacchetto completo.",
  "totti alla roma era qualcosa che non si replicherà mai più. CLAMOROSO.",
  "totti alla roma era qualcosa che non si replicherà mai più. è finita un'era.",
  "totti alla roma era qualcosa che non si replicherà mai più. true af.",
  "totti alla roma era qualcosa che non si replicherà mai più. detto questo, leao quando vuole è ingiocabile. il problema è che non lo vuole sempre.",
  "totti alla roma era qualcosa che non si replicherà mai più. brava gente veramente non ho parole per descriverlo.",
  "haaland segna 50 gol ma il city vincerebbe comunque senza di lui. palese.",
  "haaland segna 50 gol ma il city vincerebbe comunque senza di lui. tipo è un sistema, non un giocatore.",
  "haaland segna 50 gol ma il city vincerebbe comunque senza di lui. true af.",
  "haaland segna 50 gol ma il city vincerebbe comunque senza di lui. de bruyne è il vero motore. palese.",
  "vinicius jr è lo spettacolo del calcio mondiale in questo momento. CLAMOROSO.",
  "vinicius jr è lo spettacolo del calcio mondiale in questo momento. true af.",
  "ma poi ceh. vinicius jr è lo spettacolo del calcio mondiale in questo momento.",
  "vinicius jr è lo spettacolo del calcio mondiale. tipo è un altro livello.",
  "lamine yamal a 17 anni gioca con una maturità che non si vede a quella età. ASSURDO.",
  "lamine yamal a 17 anni gioca con una maturità che non si vede a quella età. clamoroso.",
  "ma poi ceh. lamine yamal a 17 anni gioca con una maturità che non si vede a quella età.",
  "lamine yamal a 17 anni gioca con una maturità che non si vede a quella età. palese.",
  "lamine yamal a 17 anni è già decisivo. non me lo aspettavo proprio.",
  "pirlo vedeva il gioco con 10 secondi di anticipo. un fenomeno unico. CLAMOROSO.",
  "pirlo vedeva il gioco con 10 secondi di anticipo. tipo non era calcio erano scacchi.",
  "pirlo vedeva il gioco con 10 secondi di anticipo. è finita un'era quando si è ritirato.",
  "mbappé tra 5 anni sarà il miglior giocatore del mondo senza dubbi. palese.",
  "mbappé tra 5 anni sarà il miglior giocatore del mondo. deve ancora dimostrare la continuità però. ceh.",
  "maradona aveva qualcosa che non si può allenare. era pura natura. CLAMOROSO.",
  "maradona aveva qualcosa che non si può allenare. tipo è un altro pianeta.",
  "maradona aveva qualcosa che non si può allenare. è finita un'era.",
  "buffon è il portiere più forte che l'italia abbia mai espresso. palese.",
  "buffon è il portiere più forte che l'italia abbia mai espresso. CLAMOROSO come carriera.",
  "baresi difendeva con l'intelligenza prima che con il fisico. fenomenale. palese.",
  "baresi difendeva con l'intelligenza prima che con il fisico. tipo non era difesa era lettura del gioco.",
  "zidane in campo era arte. non calcio. arte. palese.",
  "zidane in campo era arte. non calcio. arte. CLAMOROSO.",
  "ronaldinho era felicità pura. nessuno si è mai divertito quanto lui. true af.",
  "ronaldinho era felicità pura. nessuno si è mai divertito quanto lui. è finita un'era.",
  "del piero era eleganza pura. un tocco che pochi hanno avuto nella storia. palese.",
  "inzaghi segnava gol che sembravano impossibili. era posizionamento puro. true af.",
  "cannavaro nel 2006 era un muro invalicabile. pallone d'oro meritatissimo. CLAMOROSO.",
  "baggio nel '94 portò l'italia in finale con i suoi gol. poi quel rigore. eh beh.",
  "maldini è il simbolo di quello che dovrebbe essere un difensore. palese.",
  "thiago silva ha difeso ad alto livello fino a quasi 40 anni. rispetto. true af.",
  "roberto carlos aveva un sinistro che sembrava fisicamente impossibile. ASSURDO.",
  "pedri avrebbe giocato in qualsiasi squadra della storia del calcio. clamoroso.",
  "toni kroos ha vinto tutto quello che si può vincere. silenziosamente. true af.",
  "neymar aveva il talento per essere il migliore. la testa lo ha frenato. eh beh.",
  "lukaku fisicamente è devastante. tecnicamente può fare di più. ceh.",
  "barella è il centrocampista più continuo d'europa in questo momento. BOMBA.",
  "dybala è un fantasista puro. in italia non li valorizzano. palese.",
  "bellingham ha tutto: fisico, tecnica, gol, personalità. il pacchetto completo. CLAMOROSO.",
  "de bruyne è il centrocampista più completo del calcio moderno. true af.",
  "leao quando vuole è ingiocabile. il problema è che non lo vuole sempre. ceh.",
  "sam kerr segna gol impossibili. sottovalutatissima fuori dall'australia. assurdo.",
  "benzema è stato il centravanti più sottovalutato della sua generazione. palese.",
  "modric a 36 anni gioca ancora meglio di metà dei centrocampisti in circolazione. assurdo.",
  "iniesta era il calcio che ti fa venire voglia di giocare. tipo non c'è altro modo per dirlo.",
  "xavi ha costruito il barca dopo aver costruito il barca come giocatore. clamoroso.",
  "klopp ha cambiato il modo di pensare al calcio. punto.",
  "guardiola è il miglior allenatore della storia moderna. non si discute.",
  "mourinho era entertainment puro. nel bene e nel male.",
  "capello all'estero vinceva sempre. in italia lo hanno snobbato troppo. palese.",
  "sacchi ha rivoluzionato il calcio italiano. brava gente, un fenomeno unico.",
  "trapattoni era il calcio di una volta. nel senso migliore possibile.",
  "conte trasforma qualsiasi squadra gli metti sotto. vero o no.",
  "ancelotti vince ovunque va. è la prova che conta più la gestione dei campioni che il sistema.",
  "lukaku alla roma sembrava il solito lukaku in difficoltà. e invece.",
  "osimhen è il centravanti più forte della serie a di questo momento. vero.",
  "kvara è un talento assurdo. spero rimanga in italia ancora un po'.",
  "chiesa quando è al 100% cambia le partite. il problema è che non è quasi mai al 100%.",
  "theo hernandez è il terzino più forte del campionato italiano. easy.",
  "maignan è il miglior portiere della serie a. palese.",
  "calabria capitano del milan. una roba che non avrei mai immaginato.",
  "il napoli senza osimhen è un'altra squadra. nel senso peggiore.",
  "la juve senza uno scudetto da anni. roba che fa effetto.",
  "l'inter sta costruendo qualcosa di solido. rispetto.",
  "la roma di de rossi giocava un bel calcio. purtroppo.",
  "l'atalanta continua a stupire ogni anno. e ogni anno ci sorprendiamo. palese.",
  "il bologna in champions. una roba clamorosa per chi li guardava anni fa.",
  "la fiorentina di italiano era bella da vedere. true af.",
  "il milan era fortissimo nel 2022. poi qualcosa si è rotto.",
  "l'italia agli europei aveva una roba assurda. poi il mondiale...",
  "donnarumma al psg sembra un pesce fuor d'acqua spesso. ceh.",
  "verratti era uno dei centrocampisti più forti d'europa. punto.",
  "el shaarawy è tornato ed è ancora clamoroso.",
  "zaniolo poteva diventare qualcosa di enorme. la testa lo ha frenato come neymar.",
  "pellegrini è sottovalutato fuori dalla roma. palese.",
  "spinazzola terzino sinistro più forte d'italia quando è sano. true af.",
  "mancini ct dell'italia aveva costruito qualcosa di bello. poi l'arabia.",
  "spalletti ct è un'altra cosa rispetto a mancini. nel senso tattico.",
  "l'under 21 italiana ha talenti assurdi. basta dargli tempo.",
  "retegui centravanti della nazionale. una storia assurda e bella insieme.",
  "cambiaso è uno dei terzini più interessanti d'europa adesso. clamoroso.",

  // === CALCIO - OPINIONI IMPOPOLARI ===
  "unpopular opinion: il calcio di guardiola è bellissimo ma noioso da guardare in tv.",
  "il var ha rovinato le emozioni del calcio. punto. non si torna indietro ma era meglio prima.",
  "i mondiali ogni due anni sarebbero una roba orrenda. per fortuna non si è fatto.",
  "la champions league con 36 squadre è troppo. ha già perso fascino.",
  "i rigori come sistema per decidere le partite non ha senso nel 2024. servirebbe qualcosa di meglio.",
  "il calcio femminile merita più attenzione. punto. non è opinione è fatto.",
  "troppi stranieri in serie a stanno uccidendo il settore giovanile italiano. vero o no.",
  "gli stadi italiani sono un problema enorme. e nessuno fa niente.",
  "la serie b italiana è più interessante della serie a come spettacolo. clamoroso ma vero.",
  "il fantacalcio ha rovinato il modo in cui guardiamo le partite. parlo per esperienza.",
  "i procuratori guadagnano troppo nel calcio. è il vero cancro del sistema.",
  "i social media hanno reso i calciatori meno simpatici. troppo curati, troppo filtrati.",
  "il calcio degli anni 90 era più bello da guardare. unpopular ma vero.",
  "gli ultras hanno ancora un ruolo importante nella cultura calcistica. nel bene e nel male.",
  "i tifosi che fischiano la propria squadra fanno più danno che bene. palese.",

  // === BASKET NBA ===
  "lebron è il più forte di tutti i tempi nel basket. michael jordan è un'icona ma lebron ha fatto di più.",
  "michael jordan non avrebbe dominato nell'nba moderna. cambiatemi l'idea.",
  "lebron ha vinto con tre squadre diverse. questo la dice lunga su chi è il goat.",
  "curry ha cambiato il basket per sempre. il tiro da tre non è mai stato lo stesso dopo di lui.",
  "curry è il giocatore che ha avuto più impatto sul basket moderno. palese.",
  "giannis è un fenomeno fisico che si è costruito tecnicamente. rispetto enorme.",
  "nikola jokic è il centro più completo della storia del basket. clamoroso.",
  "luka doncic sarà il goat della sua generazione. aspettiamo ma sembra ovvio.",
  "ja morant è il giocatore più entusiasmante dell'nba quando è in campo. true af.",
  "wembanyama è una roba che non si era mai vista. è letteralmente unico.",
  "shaq era inarrestabile. nessuno ha mai avuto quel dominio fisico.",
  "kobe era il più duro mentalmente. punto.",
  "kobe e jordan erano la stessa roba: winners ossessionati. nel senso migliore.",
  "tim duncan è il giocatore più sottovalutato della storia nba. vero o no.",
  "il basket moderno è più tecnico ma meno fisico. dipende se ti piace o no.",
  "i golden state warriors di curry hanno cambiato il gioco più di qualsiasi altra squadra degli ultimi 20 anni.",
  "boston celtics sono la squadra più forte dell'est adesso. palese.",
  "denver ha vinto il titolo con jokic e tutti se ne sono già dimenticati. assurdo.",
  "anthony davis quando è motivato è il giocatore più dominante dell'nba. il problema è il quando.",
  "kevin durant è il giocatore più difficile da marcare della storia. true af.",

  // === TENNIS ===
  "federer, nadal e djokovic hanno alzato l'asticella del tennis a un livello impossibile per chiunque altro.",
  "djokovic è il goat del tennis. i numeri parlano chiaro.",
  "nadal al roland garros era semplicemente un'altra dimensione. CLAMOROSO.",
  "federer era il tennista più bello da guardare di tutti i tempi. unpopular forse ma vero.",
  "sinner numero uno al mondo. una roba clamorosa per il tennis italiano.",
  "sinner è già nella conversazione dei più forti di sempre e ha 23 anni. assurdo.",
  "alcaraz è l'erede naturale di federer nel modo di giocare. palese.",
  "la rivalità sinner-alcaraz sarà quella che definirà il tennis dei prossimi 10 anni.",
  "berrettini quando sta bene è top 5 mondiale. il problema è che non sta mai bene.",
  "musetti ha un talento clamoroso. spero riesca a esprimerlo con continuità.",

  // === FORMULA 1 ===
  "hamilton è il più forte pilota di formula 1 di tutti i tempi. i numeri non mentono.",
  "schumacher al suo picco era inarrestabile. true af.",
  "verstappen è dominante in modo assurdo. è difficile anche solo criticarlo.",
  "verstappen con quella red bull è come messi con l'argentina: impossibile separare il pilota dalla macchina.",
  "leclerc merita una ferrari competitiva. è uno dei migliori piloti in griglia.",
  "la ferrari delude ogni anno e ogni anno ci sorprendiamo. brava gente.",
  "sainz è più forte di quanto la ferrari gli abbia permesso di dimostrare. vero.",
  "norris è il pilota più sottovalutato dell'ultimo periodo. palese.",
  "la formula 1 con la netflix drive to survive è diventata uno sport diverso. nel bene e nel male.",
  "il gp di monza è il migliore del calendario. punto. tifo italiano a parte.",
  "hamilton alla ferrari è una storia clamorosa. speriamo finisca bene.",
  "russell è più forte di quanto sembri quando guida la mercedes peggiore.",

  // === FILM E SERIE TV ===
  "il padrino è il film più perfetto mai realizzato. punto.",
  "il padrino 2 è ancora meglio del primo. unpopular ma vero.",
  "breaking bad è la serie tv più perfetta mai scritta. non si discute.",
  "breaking bad vs sopranos è il dibattito più noioso del mondo. sono due cose diverse.",
  "i sopranos è la serie che ha inventato il modo moderno di fare tv. palese.",
  "the wire è la serie più sottovalutata della storia della televisione. brava gente guardatela.",
  "game of thrones ha avuto il finale peggiore della storia delle serie tv. clamoroso quanto è caduta.",
  "game of thrones stagione 1-4 è ancora oggi roba di un livello clamoroso.",
  "stranger things dopo la seconda stagione ha perso qualcosa. vero o no.",
  "la casa di carta è diventata insopportabile dalla terza stagione. palese.",
  "squid game era overhyped ma la prima stagione era comunque solida.",
  "succession è la serie più sottovalutata degli ultimi anni. true af.",
  "succession finale era perfetto. uno dei migliori mai girati.",
  "peaky blinders nelle ultime stagioni ha perso il filo. ceh.",
  "chernobyl è la miniserie più perfetta mai realizzata. non si discute.",
  "true detective stagione 1 è il picco assoluto della tv americana. palese.",
  "true detective stagione 2 non esiste. è un fatto.",
  "the bear è la serie più ansiogena degli ultimi anni. nel senso migliore.",
  "the last of us prima stagione era cinema vero. chapeau.",
  "white lotus è la serie più intelligente degli ultimi anni. true af.",
  "severance ha l'idea più originale vista in tv da anni. CLAMOROSO.",
  "dark è la serie tedesca che tutti dovrebbero vedere almeno una volta. palese.",
  "ozark è sottovalutata rispetto a breaking bad ma è roba dello stesso livello.",
  "yellowstone non capisco perché abbia questo successo. genuina domanda.",
  "the boys è la critica al capitalismo americano più divertente che esista. true af.",
  "invincible è l'animazione più seria e violenta che esista. assurdo quanto è bona.",
  "arcane è la migliore serie animata degli ultimi 10 anni. non si discute.",
  "avatar la via dell'acqua visivamente è un capolavoro. narrativamente meno.",
  "top gun maverick è il film d'azione più soddisfacente degli ultimi anni. palese.",
  "oppenheimer è il film più importante degli ultimi 10 anni. true af.",
  "barbie e oppenheimer lo stesso giorno era una roba storica. clamoroso.",
  "nolan è il regista più importante della sua generazione. punto.",
  "quentin tarantino non ha fatto un brutto film in vita sua. vero o no.",
  "inglourious basterds è il film più divertente degli ultimi 20 anni. palese.",
  "pulp fiction è ancora oggi un film impossibile da replicare. true af.",
  "scorsese a 80 anni fa ancora i film migliori del cinema americano. rispetto.",
  "killers of the flower moon era lungo ma ogni minuto valeva. clamoroso.",
  "the irishman era lungo ma perfetto. ceh.",
  "wolf of wall street è il film più energico degli ultimi 20 anni. BOMBA.",
  "poor things di lanthimos è roba di un altro pianeta. assurdo.",
  "la zona d'interesse è il film più inquietante degli ultimi anni. nel senso migliore.",
  "past lives è il film romantico più maturo degli ultimi anni. true af.",
  "all quiet on the western front è devastante. guardatelo.",
  "everything everywhere all at once è pazzesco. non so come spiegarlo altrimenti.",
  "the lighthouse di eggers è il film più strano e affascinante degli ultimi anni. palese.",
  "hereditary è il film horror più disturbante del decennio. true af.",
  "ari aster è il regista horror più interessante adesso. palese.",
  "midsommar è un film horror che fa paura anche di giorno. assurdo.",
  "beau is afraid è il film più incomprensibile degli ultimi anni. nel senso positivo.",
  "il gladiatore 2 era inutile. il primo non aveva bisogno di un sequel.",
  "dune parte 2 ha superato le aspettative altissime. CLAMOROSO.",
  "denis villeneuve è il miglior regista di fantascienza vivo. palese.",
  "arrival è il film di fantascienza più intelligente degli ultimi 20 anni. true af.",
  "blade runner 2049 è un capolavoro che il pubblico non ha meritato al cinema.",
  "inception è il film che ha fatto credere a tutti di essere intelligenti. nel senso ironico.",
  "interstellar visivamente è un capolavoro. il finale è discutibile.",
  "the dark knight è ancora il miglior film su un supereroe mai fatto. punto.",
  "i film marvel stanno diventando sempre più irrilevanti. vero o no.",
  "endgame era una roba storica al cinema. tutto quello dopo è stato downhill.",
  "spider-man no way home era fan service puro ma funzionava. palese.",
  "i film dc non sanno cosa vogliono essere. è il vero problema.",
  "the batman di pattinson era il miglior film dc degli ultimi anni. true af.",
  "joker con phoenix è un film che non dimentichi. nel bene e nel male.",
  "joker 2 era un errore clamoroso. non capisco cosa volessero fare.",
  "parasite di bong joon-ho è il film più meritevole di tutti i premi che ha vinto. palese.",
  "drive è il film con la colonna sonora più iconica degli ultimi 20 anni.",
  "2001 odissea nello spazio è ancora il film più avanzato mai girato. true af.",
  "stanley kubrick è il regista più importante della storia del cinema. punto.",
  "shining è ancora il miglior film horror di tutti i tempi. palese.",
  "il silenzio degli innocenti dopo 30 anni fa ancora paura. assurdo.",
  "forrest gump è il film più sopravvalutato degli anni 90. unpopular ma vero.",
  "titanic era cinema popolare fatto benissimo. rispetto per cameron.",
  "avatar il primo era visivamente rivoluzionario ma narrativamente vuoto. vero.",
  "matrix è ancora il film più influente degli ultimi 30 anni. palese.",
  "fight club invecchia meglio di qualsiasi altro film degli anni 90. true af.",
  "american beauty non regge alla prova del tempo. cambiatemi l'idea.",
  "american history x è ancora devastante. guardatelo se non l'avete visto.",
  "requiem for a dream è il film più difficile da rivedere di sempre. ceh.",
  "il grande lebowski è il film più quotabile della storia. palese.",
  "goodfellas è il miglior film di scorsese. punto.",
  "il fu... no, goodfellas batte il padrino. unpopular opinion clamorosa.",
  "once upon a time in hollywood è il film più rilassante di tarantino. true af.",

  // === MUSICA ===
  "kendrick lamar è il miglior rapper vivente. palese.",
  "kendrick vs drake era una roba storica. e kendrick ha vinto su tutti i fronti.",
  "not like us è la diss track più devastante degli ultimi 10 anni. CLAMOROSO.",
  "drake ha venduto tantissimo ma non è mai stato davvero il migliore. vero o no.",
  "kanye west prima del 2016 era geniale. dopo è un'altra storia.",
  "my beautiful dark twisted fantasy è l'album hip hop più perfetto mai realizzato. palese.",
  "graduation di kanye è ancora oggi uno degli album più ascoltabili della storia. true af.",
  "jay-z è il rapper più intellettualmente solido della storia. punto.",
  "the blueprint è il miglior album di jay-z e forse il miglior album rap di sempre.",
  "eminem nel suo periodo d'oro era su un livello tecnico impossibile. CLAMOROSO.",
  "marshal mathers lp è ancora il disco più scuro e onesto mai inciso. true af.",
  "tyler the creator ha il miglior sviluppo artistico del rap degli ultimi 10 anni. palese.",
  "igor di tyler è un capolavoro assoluto. non si discute.",
  "call me if you get lost era tyler al suo picco come storyteller. true af.",
  "frank ocean channel orange è l'album r&b più importante del decennio scorso.",
  "blonde di frank ocean è ascoltare qualcuno che pensa ad alta voce. clamoroso.",
  "sza è la voce più interessante del r&b moderno. palese.",
  "beyoncé renaissance era un momento storico per la musica dance. BOMBA.",
  "beyoncé cowboy carter dimostra che può fare qualsiasi cosa. assurdo.",
  "taylor swift è l'artista più intelligente nella gestione della propria carriera. vero.",
  "folklore di taylor swift è il suo album migliore. unpopular ma vero.",
  "the weeknd ha avuto il picco più alto e il declino più veloce degli ultimi anni. ceh.",
  "after hours era un album perfetto. quasi tutto dopo era un po' meno.",
  "bad bunny ha reso il reggaeton qualcosa di più serio. rispetto.",
  "un verano sin ti è uno degli album più ascoltati della storia per un motivo.",
  "billie eilish when we all fall asleep è ancora freschissimo. true af.",
  "olivia rodrigo sour era un album di debutto clamoroso per la sua età.",
  "harry styles è sopravvalutato come solista. unpopular ma vero.",
  "coldplay ha fatto i due album migliori e poi ha scelto la via commerciale. palese.",
  "radiohead ok computer è ancora il miglior album rock degli ultimi 30 anni. punto.",
  "kid a di radiohead era troppo avanti per il suo tempo. clamoroso.",
  "arctic monkeys whatever people say i am è ancora uno degli album di debutto migliori di sempre.",
  "am degli arctic monkeys è il loro capolavoro. vero o no.",
  "tame impala lonerism e currents sono capolavori assoluti. palese.",
  "daft punk random access memories era un evento. la loro fine era inevitabile.",
  "get lucky di daft punk è ancora la canzone più bella degli anni 2010. true af.",
  "the strokes is this it è ancora freschissimo dopo vent'anni. clamoroso.",
  "lcd soundsystem sound of silver è il miglior album indie del decennio scorso. palese.",
  "phoebe bridgers punisher è il disco più triste e bello degli ultimi anni. true af.",
  "bo burnham inside è il progetto artistico più onesto del covid. clamoroso.",
  "lana del rey born to die era incompresa all'epoca. ora è riconosciuta come capolavoro. palese.",
  "ultraviolence di lana del rey è il suo album più coraggioso. true af.",
  "adele 21 è ancora il miglior album pop del decennio scorso. brava gente.",
  "amy winehouse back to black è uno degli album più perfetti mai registrati. punto.",
  "la morte di amy winehouse è ancora una delle più grandi perdite della musica moderna.",
  "michael jackson thriller è ancora l'album più venduto di tutti i tempi per un motivo.",
  "prince era un genio incompreso dalla maggior parte delle persone. palese.",
  "purple rain di prince è il miglior album degli anni 80. unpopular ma vero.",
  "david bowie aveva un alter ego diverso per ogni decennio e li vinceva tutti. CLAMOROSO.",
  "ziggy stardust di bowie è ancora oggi rivoluzionario. true af.",
  "i beatles hanno fatto tutto prima di tutti. punto.",
  "abbey road è il miglior album dei beatles. dibattito aperto.",
  "led zeppelin iv è il miglior album rock di tutti i tempi. palese.",
  "pink floyd the wall è il più ambizioso album rock della storia. true af.",
  "dark side of the moon non ha un secondo brutto. clamoroso.",
  "nirvana nevermind ha cambiato la musica in tre minuti. assurdo pensarci.",
  "kurt cobain era il cantante più onesto della sua generazione. palese.",
  "pearl jam ten è il miglior album grunge. unpopular rispetto a nevermind ma vero.",
  "metallica master of puppets è il miglior album metal di sempre. punto.",
  "// MUSICA ITALIANA",
  "gué è il rapper italiano più tecnico della sua generazione. palese.",
  "fastlife 4 di gué è il suo capolavoro. true af.",
  "night skinny ha un sound che nessuno riesce a replicare. CLAMOROSO.",
  "salmo è il rapper italiano più completo degli ultimi 10 anni. vero.",
  "machete crew ha ridefinito il rap italiano. punto.",
  "marracash è il rapper italiano più letterario. palese.",
  "noi loro gli altri di marracash è l'album rap italiano più importante del decennio.",
  "sfera ebbasta ha aperto le porte del rap italiano al pubblico mainstream. nel bene e nel male.",
  "capo plaza ha il flow più naturale del trap italiano. true af.",
  "lazza ha avuto la carriera più in crescita degli ultimi anni nel rap italiano. clamoroso.",
  "geolier sta portando il napoletano nel mainstream musicale italiano. assurdo in senso positivo.",
  "axell è uno dei producer italiani più interessanti in circolazione. palese.",
  "tony effe ha scelto il lato commerciale e ha funzionato. rispetto per la strategia.",
  "il rap italiano non valorizza abbastanza i producer. true af.",
  "sanremo ha smesso di essere un festival di nicchia ed è diventato il super bowl italiano.",
  "mahmood è l'artista italiano più completo degli ultimi anni. palese.",
  "blanco ha un talento clamoroso. speriamo che non si bruci.",
  "tiziano ferro è il cantautore pop italiano più importante degli ultimi 20 anni. true af.",
  "vasco rossi live è ancora oggi uno spettacolo che non ha paragoni in italia. clamoroso.",
  "lucio battisti è ancora oggi il musicista italiano più influente di sempre. palese.",
  "de andrè è il poeta italiano più importante del novecento. punto.",
  "franco battiato era un genio incompreso dal grande pubblico per troppo tempo. vero.",

  // === TECNOLOGIA ===
  "l'iphone non è più innovativo come una volta. e tutti lo sanno.",
  "android vs iphone è il dibattito più inutile del mondo. usa quello che vuoi.",
  "l'ia cambierà tutto nei prossimi 5 anni. nel bene e nel male.",
  "chatgpt ha reso tutti più pigri o più produttivi. dipende dalla persona.",
  "l'ia non sostituirà la creatività umana. la aumenterà. palese.",
  "social media hanno fatto più danni che bene alla salute mentale delle persone. vero.",
  "instagram non è più quello di una volta. è diventato tiktok ma peggio.",
  "tiktok ha cambiato l'attenzione delle persone in modo irreversibile. assurdo.",
  "twitter/x sotto elon musk è diventato irriconoscibile. nel senso peggiore.",
  "facebook è morto per i giovani. è un social per over 40 adesso. palese.",
  "linkedin è il social più imbarazzante che esista. true af.",
  "il metaverso di meta era la cosa più inutile mai annunciata. clamoroso quanto abbiano speso.",
  "apple vision pro è interessante ma non capisce ancora dove vuole andare.",
  "la realtà virtuale non è ancora pronta per il mainstream. ceh.",
  "elon musk è il personaggio più controverso dell'era tecnologica. palese.",
  "tesla ha cambiato il mercato delle auto elettriche. questo è innegabile.",
  "le auto elettriche sono il futuro ma l'infrastruttura non è ancora pronta. vero.",
  "spotify ha cambiato il modo di ascoltare musica per sempre. nel bene e nel male.",
  "netflix con i prezzi alti e la pubblicità ha perso la sua identità originale. ceh.",
  "prime video ha contenuti clamorosi ma nessuno lo usa come main platform. assurdo.",
  "i videogiochi sono diventati un'industria più grande del cinema. e nessuno se ne parla abbastanza.",
  "the last of us parte 1 è il videogioco più cinematografico mai realizzato. palese.",
  "red dead redemption 2 è il videogioco con il mondo aperto più bello mai creato. true af.",
  "elden ring è il videogioco più soddisfacente degli ultimi anni. CLAMOROSO.",
  "breath of the wild ha ridefinito il genere action adventure. punto.",
  "minecraft è il videogioco più influente di tutti i tempi. palese.",
  "gta 6 è il gioco più atteso della storia dei videogiochi. easy.",
  "i giochi con microtransazioni sono il problema più grande del gaming moderno. vero.",
  "pc master race vs console è il dibattito più inutile del gaming. palese.",

  // === OPINIONI RANDOM / VITA ===
  "le persone che non rispondono ai messaggi ma sono attive sui social sono incomprensibili. ceh.",
  "chi mette la sveglia ogni 5 minuti è la persona più coraggiosa del mondo o la più stupida. non so quale.",
  "i lunedì mattina sono il momento più sopravvalutato della settimana. true af.",
  "i fine settimana sembrano sempre più corti dei giorni feriali. assurdo.",
  "l'estate è sopravvalutata. settembre è il mese migliore dell'anno. palese.",
  "il caffè è l'unica cosa che rende sopportabile la mattina. punto.",
  "la pizza napoletana vs la pizza romana è il dibattito più serio che esiste in italia. ceh.",
  "la pasta al pomodoro fatta bene batte qualsiasi cosa. true af.",
  "il cibo italiano è il migliore del mondo. non si discute.",
  "chi dice che il sushi è meglio della pasta ha semplicemente torto. palese.",
  "i ristoranti troppo rumorosi rovinano l'esperienza. vero o no.",
  "gli aperitivi milanesi sono diventati troppo costosi. clamoroso quanto si spende.",
  "roma vs milano come città è il dibattito più inutile degli italiani. both have pros.",
  "napoli è la città più viva e caotica d'italia. nel senso migliore possibile.",
  "la sardegna ha il mare più bello d'europa. punto.",
  "le dolomiti sono la cosa più bella d'italia che gli italiani apprezzano meno. palese.",
  "l'autostrada italiana è un'esperienza unica nel suo genere. e non in modo positivo.",
  "i treni ad alta velocità italiani sono tra i migliori d'europa. brava gente.",
  "trenitalia però in ritardo è uno sport nazionale. true af.",
  "il prezzo delle case nelle grandi città è diventato assurdo. una roba di cui non parliamo abbastanza.",
  "lo smart working ha cambiato il modo di lavorare per sempre. nel bene e nel male.",
  "chi dice che stare in ufficio è meglio non ha mai provato a lavorare da casa seriamente. ceh.",
  "le riunioni che potevano essere email sono il cancro del lavoro moderno. palese.",
  "le persone che non sanno dire no sono quelle che lavorano di più e vengono rispettate di meno. assurdo.",
  "i bonus aziendali sono spesso usati per non pagare gli stipendi giusti. vero.",
  "laurearsi in italia vale ancora qualcosa? dibattito aperto.",
  "il sistema universitario italiano è tra i migliori al mondo e tra i meno riconosciuti. clamoroso.",
  "studiare all'estero ti cambia la prospettiva in modo irreversibile. palese.",
  "imparare l'inglese bene è ancora la skill più utile che puoi avere nel 2024. true af.",
  "il teatro è la forma d'arte più sottovalutata della cultura moderna. palese.",
  "i musei gratuiti la domenica sono una delle cose più belle dello stato italiano. vero.",
  "leggere libri fisici è un'esperienza che nessun ebook può replicare. true af.",
  "chi dice di non avere tempo per leggere ha semplicemente altre priorità. ceh.",
  "dormire 8 ore è la cosa più produttiva che puoi fare. palese.",
  "la palestra è sottovalutata come strumento di salute mentale. true af.",
  "correre è gratis ed è la migliore terapia che esista. palese.",
  "il nuoto è lo sport più completo che esista. punto.",
  "lo yoga non è per tutti ma per chi funziona, funziona davvero. ceh.",
  "meditare è difficile ma chi riesce a farlo regolarmente ha qualcosa in più. palese.",
  "i cani sono superiori ai gatti. unpopular in certi circoli ma vero.",
  "i gatti sono superiori ai cani. true af. palese.",
  "avere una pianta in casa cambia l'energia del posto. assurdo ma vero.",
  "viaggiare da soli almeno una volta nella vita è obbligatorio. palese.",
  "i viaggi con gli amici sono quelli che rimangono più impressi. true af.",
  "i viaggi organizzati in gruppo sono orrendi. unpopular ma vero.",
  "il giappone è il paese più diverso e affascinante che si possa visitare. CLAMOROSO.",
  "la spagna è il paese europeo con la qualità della vita migliore. palese.",
  "portogallo è la scoperta più bella degli ultimi anni per i turisti. true af.",
  "new york è la città più energica del mondo. punto.",
  "tokyo è la città più efficiente del mondo. clamoroso quanto funzioni tutto.",
  "amsterdam è la città europea più vivibile. palese.",
  "londra è sopravvalutata rispetto al costo della vita. unpopular.",
  "parigi è bella ma i parigini la rovinano. ceh.",

  // === SPORT VARI ===
  "usain bolt è il più grande atleta di tutti i tempi. punto.",
  "michael phelps è il più grande olimpionico della storia. palese.",
  "simone biles è la ginnasta più forte mai vista. CLAMOROSO.",
  "roger federer come personalità nello sport non ha eguali. true af.",
  "il tour de france è lo sport più brutale che esista come fatica fisica. assurdo.",
  "il rugby è il più onesto degli sport di squadra. palese.",
  "il cricket è incomprensibile per chi non ci è cresciuto. ceh.",
  "il golf è lo sport più sottovalutato come difficoltà tecnica. true af.",
  "tiger woods ai suoi massimi era qualcosa che non si era mai visto nel golf. CLAMOROSO.",
  "il padel ha salvato la vita sociale di milioni di italiani. palese.",
  "il padel ha rovinato il tennis amatoriale in italia. unpopular ma vero.",
  "il ciclismo su pista è lo sport più sottovalutato delle olimpiadi. true af.",
  "le olimpiadi di parigi 2024 sono state clamorose per l'italia. assurdo quanto abbiamo vinto.",
  "marcell jacobs che vince i 100 metri era roba da non credere. BOMBA.",
  "gianmarco tamberi è il personaggio più simpatico dello sport italiano. palese.",
  "la nazionale italiana di volley è una gioia da guardare. true af.",
  "paola egonu è la giocatrice più forte del mondo nel volley. CLAMOROSO.",
  "il nuoto italiano ha avuto una generazione clamorosa negli ultimi anni. brava gente.",
  "gregorio paltrinieri è uno degli atleti italiani più mentalmente forti. palese.",
  "federica pellegrini è ancora la sportiva italiana più iconica degli ultimi 20 anni. true af.",

  // === STILE ANZIANO / PIÙ SERIO ===
  "Messi è senza dubbio il calciatore più forte che il mondo abbia mai visto. I numeri parlano da soli.",
  "Il calcio degli anni Novanta aveva qualcosa che il calcio moderno non riuscirà mai a replicare.",
  "Totti è stato l'ultimo grande giocatore rimasto fedele alla sua squadra per tutta la carriera. Una cosa rara.",
  "La Juventus senza i nove scudetti consecutivi è una squadra diversa. Stanno cercando una nuova identità.",
  "Il Milan di Sacchi negli anni Ottanta ha cambiato il calcio europeo. Questo è un fatto storico.",
  "Pirlo era un genio incompreso dal grande pubblico. Solo gli appassionati sapevano davvero cosa stessero guardando.",
  "Il calcio italiano ha perso qualcosa di importante negli ultimi vent'anni. Non solo i risultati, ma l'identità.",
  "Sinner ha dimostrato che l'Italia può produrre campioni nel tennis. Ci voleva solo il sistema giusto.",
  "La Ferrari in Formula 1 continua a deludere nonostante i talenti in griglia. Il problema è organizzativo.",
  "Hamilton ha vinto sette mondiali. Chiunque dica che non è il più grande nella storia della Formula 1 nega l'evidenza.",
  "Il cinema americano degli anni Settanta è stato il periodo più creativo della storia cinematografica mondiale.",
  "Scorsese a ottant'anni continua a fare film migliori di registi con metà dei suoi anni. Questo la dice lunga.",
  "La televisione americana degli anni Duemila ha prodotto più capolavori di quanto la memoria collettiva ricordi.",
  "I Sopranos ha inventato un nuovo linguaggio televisivo che ancora oggi viene imitato. Un'opera fondamentale.",
  "La musica degli anni Novanta era incredibilmente varia. Grunge, britpop, hip hop dorato. Un decennio unico.",
  "Amy Winehouse se fosse vissuta avrebbe probabilmente cambiato la musica popolare in modo definitivo.",
  "I Beatles in sette anni hanno attraversato più epoche musicali di quanto molti artisti facciano in una carriera.",
  "L'intelligenza artificiale pone domande sulla creatività umana che non avevamo mai dovuto affrontare prima.",
  "I social media hanno trasformato il modo in cui le persone costruiscono la propria identità. Non sempre in meglio.",
  "Il costo della vita nelle grandi città italiane è diventato insostenibile per i giovani. È un problema strutturale.",
  "Lo sport ha il potere unico di unire persone che non avrebbero mai niente da dirsi. È la sua magia.",
  "Leggere rimane il modo più efficace per sviluppare il pensiero critico. Non c'è alternativa reale.",
  "Viaggiare cambia le persone in modo profondo. Vedere come vivono gli altri ridimensiona i propri problemi.",
  "Il teatro è un'esperienza che il cinema non può replicare. La presenza degli attori cambia tutto.",
  "La cucina italiana è un patrimonio culturale che spesso diamo per scontato. Non dovremmo.",
  "Gli stadi italiani sono il riflesso di un problema più grande: la difficoltà del paese di investire in infrastrutture.",
  "Buffon ha rappresentato la serietà professionale per vent'anni. Un modello raro nello sport moderno.",
  "Valentino Rossi era più di un pilota. Era un personaggio che aveva reso la MotoGP uno spettacolo globale.",
  "Alberto Tomba ha reso lo sci alpino uno sport popolare in Italia. Un'impresa quasi impossibile.",

  // === STILE GIOVANE VELOCE ===
  "messi goat no cap",
  "jordan > lebron sorry not sorry",
  "breaking bad > tutto il resto. period.",
  "kendrick won. full stop.",
  "lamine yamal a 17 anni è già top 5 al mondo wtf",
  "sinner numero 1 del mondo lets gooo",
  "oppenheimer era cinema puro ngl",
  "succession finale era perfetto fr fr",
  "tyler igor is a masterpiece periodt",
  "elden ring game of the decade easy",
  "dune 2 exceeded every expectation no cap",
  "the bear è troppo ansiogena aiuto",
  "arcane stagione 1 era cinema animated fr",
  "jokic è il mvp più sottovalutato della storia nba lowkey",
  "wembanyama è un glitch nel codice della natura",
  "paola egonu è un fenomeno della natura tbh",
  "il padel ha salvato le amicizie degli italiani lmao",
  "tokyo è la città più sicura ed efficiente del mondo no cap",
  "frank ocean blonde è un capolavoro intoccabile periodt",
  "kendrick vs drake era il beef più hype degli ultimi anni e kenny ha vinto 10-0",
  "bad bunny has been that guy for years and people are just now catching on",
  "nolan è il goat del cinema mainstream moderno no debate",
  "severance ha il plot twist più assurdo degli ultimi anni literally",
  "the last of us il gioco è ancora superiore alla serie comunque",
  "gta 6 better drop soon im losing my mind",
  "ronaldinho era pure joy to watch honestly",
  "barella è one of us e si vede nel modo migliore",
  "totti era different fr. una roba che non si vedrà più",
  "il padrino 2 hits different ogni volta che lo rivedi tbh",
  "dark german series è incomprensibile ma anche impossibile smettere di guardare",
  "vasco live è un'altra dimensione type beat",
  "sanremo è diventato il super bowl italiano e onestamente funziona",
  "geolier sta eating fr nel rap italiano",
  "salmo è criminalmente sottovalutato a livello europeo lowkey",
  "marracash è il più letterario del rap italiano no cap",
  "the weeknd after hours era a vibe from start to finish",
  "olivia rodrigo sour era un debut clamoroso ngl",
  "daft punk discovery is a perfect album no skips",
  "radiohead ok computer still hits different after all these years",
  "arctic monkeys am era il loro peak e lo sanno anche loro",
  "coldplay viva la vida era the last time they were actually interesting",
  "zidane playing football was just different bro. art.",
  "pirlo era built different ngl",
  "lebron still in the convo at 40 is genuinely insane",
  "curry changed the game permanently. the nba before and after curry is different",
  "true detective season 1 is still the best tv ever made imo",
  "parasite winning best picture was the right call fr",
  "everything everywhere all at once makes no sense and is perfect",
  "poor things è weird af e bellissimo",
  "la zona d'interesse è il film più inquietante dell'anno senza mostrare quasi nulla",

  // === OPINIONI IMPOPOLARI EXTRA ===
  "il panettone è meglio del pandoro. ho detto quello che ho detto.",
  "la colomba pasquale è sopravvalutata. e lo sa anche chi la mangia.",
  "i film di natale di netflix sono tutti uguali. eppure li guardiamo tutti.",
  "le serie tv con episodi da un'ora sono spesso dilatate di 20 minuti. tagliate.",
  "i sequel quasi mai superano l'originale. ci sono tre eccezioni nella storia del cinema.",
  "i remake dei film classici sono quasi sempre inutili. palese.",
  "il live action disney non funziona mai. e continuano a farne.",
  "il fatto che le sale cinematografiche stiano morendo è una perdita culturale enorme.",
  "vedere un film al cinema non è sostituibile dallo streaming. sono due esperienze diverse.",
  "gli oscar hanno smesso di essere rilevanti come indicatore di qualità cinematografica.",
  "i grammy non hanno mai capito il rap. e probabilmente non lo capiranno mai.",
  "spotify discover weekly è l'algoritmo più utile mai creato per la musica. palese.",
  "le playlist collaborative con gli amici sono la cosa più social che esista adesso.",
  "i concerti post-covid costano troppo. e nessuno dice niente.",
  "i festival musicali estivi sono diventati più un'esperienza social che musicale. ceh.",
  "chi fa le story dei concerti tutto il tempo e non guarda non merita di esserci. vero.",
  "i ristoranti con qr code al posto del menù fisico sono una cosa orrenda. palese.",
  "i locali senza carta di credito nel 2024 sono un problema. period.",
  "i negozi che chiudono ancora alle 13 per pausa pranzo sono un mistero italiano.",
  "la burocrazia italiana è il freno più grande alla crescita del paese. punto.",
  "il servizio sanitario nazionale italiano è ancora tra i migliori del mondo. brava gente.",
  "le code agli uffici pubblici in italia sono un'esperienza formativa. nel senso peggiore.",
  "il volontariato è la cosa più sottovalutata che una persona possa fare per sé stessa.",
  "dare la precedenza ai pedoni è uno sport di nicchia in italia. assurdo.",
  "il sistema dei rifiuti in italia è tra i più avanzati d'europa in certe zone. true af.",
  "la raccolta differenziata in italia ha fatto progressi enormi. rispetto.",
  "il cambiamento climatico è la cosa di cui parliamo di meno rispetto a quanto dovremmo. palese.",
  "le energie rinnovabili sono l'investimento più ovvio che uno stato possa fare adesso.",
  "l'italia ha un patrimonio culturale unico al mondo che non sa valorizzare abbastanza. vero.",
  "il turismo di massa sta distruggendo venezia. e lo sappiamo e non facciamo niente. ceh.",
  "il turismo responsabile non è una moda è una necessità. palese.",
  "imparare una seconda lingua cambia il modo in cui pensi. è scientifico.",
  "la filosofia dovrebbe essere insegnata meglio nelle scuole italiane. palese.",
  "la matematica è la materia più utile che si studia a scuola. punto.",
  "l'educazione finanziaria nelle scuole italiane è quasi assente. un errore enorme.",
  "investire presto è la cosa più intelligente che un giovane possa fare. true af.",
  "il mutuo prima casa è ancora la scelta migliore rispetto all'affitto in molte città. vero.",
  "i tassi di interesse alti hanno bloccato una generazione dall'acquisto di casa. assurdo.",
  "il gap generazionale in italia è più ampio che in quasi ogni altro paese europeo. ceh.",
  "i giovani italiani sono tra i più preparati d'europa ma i meno valorizzati. palese.",
  "il brain drain italiano è il problema più grave che nessuno vuole affrontare seriamente.",
  "chi torna dall'estero porta competenze che l'italia non sa usare. vero.",
  "l'italia ha bisogno di più immigrazione qualificata. è matematica demografica.",
  "la natalità in italia è un problema che richiede politiche serie non slogan. palese.",
  "il volontariato sportivo in italia è una delle cose più belle della società civile. true af.",
  "le associazioni di quartiere sono il tessuto sociale più importante che abbiamo. palese.",

  // === SPORT - ANCORA ===
  "la moto gp senza valentino rossi ha perso metà del pubblico italiano. vero.",
  "bagnaia può diventare grande come valentino. il talento c'è.",
  "la vela italiana ha avuto una stagione clamorosa. sottovalutatissima come sport.",
  "l'italia del rugby sta crescendo in modo serio. true af.",
  "la pallacanestro italiana ha prodotto giocatori clamorosi negli anni duemila. palese.",
  "gallinari quando stava bene era tra i migliori europei in nba. vero.",
  "belinelli ha fatto la carriera più longeva di un italiano in nba. rispetto.",
  "bargnani è il rimpianto più grande del basket italiano. tutto quel talento.",
  "il ciclismo italiano torna a vincere. pogacar è un fenomeno ma vingegaard lo tiene testa.",
  "pogacar è il ciclista più forte degli ultimi 10 anni. CLAMOROSO.",
  "vingegaard ha una storia personale pazzesca. tipo da film.",
  "il tour de france è ancora la corsa ciclistica più importante del mondo. palese.",
  "la boxe ha perso rilevanza rispetto agli anni 90. ceh.",
  "fury vs usyk era l'incontro più atteso da anni. e fury ha perso. assurdo.",
  "mike tyson nel suo periodo era la cosa più paurosa dello sport. punto.",
  "floyd mayweather è il pugile più intelligente tecnicamente della storia moderna. palese.",
  "la mma ha sorpassato la boxe come sport da combattimento più popolare. vero.",
  "conor mcgregor era il personaggio più grande della mma. il fighter di un'altra storia.",
  "jon jones è il fighter più dominante della storia ufc. true af.",
  "khabib era inarrestabile nel suo stile. nessuno sapeva come fermarlo.",
  "il padel è lo sport in più rapida crescita d'europa negli ultimi anni. clamoroso.",
  "il pickleball sta esplodendo negli usa. tra dieci anni lo vedremo ovunque.",
  "gli esport sono uno sport vero. chi dice di no non capisce cosa significhi competizione.",
  "il gaming professionale richiede un atletismo mentale paragonabile agli sport tradizionali. palese.",
  "il calcio a 5 è il modo migliore di godersi il calcio da adulti. true af.",
  "il nuoto in acque libere è lo sport più spirituale che esista. palese.",
  "il trail running è esploso negli ultimi anni e per buoni motivi. true af.",

  // === TECNOLOGIA EXTRA ===
  "l'ia generativa è lo strumento più potente mai messo in mano alle persone normali. clamoroso.",
  "chat gpt ha cambiato il lavoro di milioni di persone in modo permanente. palese.",
  "il problema dell'ia non è che pensa. è che pensa in base a chi la addestra.",
  "la privacy online nel 2024 è una barzelletta. e la accettiamo tutti. ceh.",
  "i cookie banner esistono solo per annoiarci. non proteggono nessuno. true af.",
  "il gdpr europeo è la legge sulla privacy più seria del mondo. palese.",
  "apple silicon è la rivoluzione più sottovalutata del computing degli ultimi anni.",
  "il mac con m1 è ancora il computer più efficiente sul mercato. true af.",
  "windows 11 è un aggiornamento che nessuno aveva chiesto. ceh.",
  "linux è superiore per chi sa usarlo. il problema è il chi sa usarlo.",
  "i videogiochi indie sono spesso più creativi dei tripla a. palese.",
  "hades è il roguelike perfetto. punto.",
  "disco elysium è il gioco più letterario mai realizzato. clamoroso.",
  "hollow knight è il metroidvania più bello di sempre. true af.",
  "celeste è il platform più emozionante degli ultimi anni. palese.",
  "among us ha dimostrato che il gameplay semplice batte sempre quello complesso se è divertente.",
  "minecraft education ha più potenziale educativo di qualsiasi software didattico tradizionale.",
  "i videogiochi educativi devono ancora trovare la formula giusta. ceh.",
  "il futuro del gaming è cloud. nel bene e nel male.",
  "il gamepass di microsoft è la proposta di valore migliore nel gaming adesso. palese.",
  "sony con le esclusive ps ha ancora il catalogo migliore. true af.",
  "nintendo fa le sue cose e continua a vincere nonostante la tecnologia non all'avanguardia. clamoroso.",
  "zelda breath of the wild è il gioco che ha ridefinito il genere open world. punto.",
  "mario è ancora il franchise di videogiochi più solido della storia. palese.",
];

const AUTHORS = [
  "AnalyticsBot99",
  "AutoPost_Alpha",
  "BotVoce42",
  "ChatterBot_IT",
  "DailyOpinion_Bot",
  "DataPulse88",
  "FeedBot_Italia",
  "HotTakeEngine",
  "InsightStream7",
  "ItaliaBot_Live",
  "MetaPost_Auto",
  "NightBot_ITA",
  "OpinionBot_24",
  "PostEngine_IT",
  "PulseBot_News",
  "RandomVoice_Bot",
  "SignalBot_Auto",
  "SocialPulse_IT",
  "SportBot_Italia",
  "TakeFactory_Bot",
  "TrendBot_ITA",
  "VoiceNode_Auto",
  "WaveBot_Italia",
];

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

async function main() {

  const text = pickRandom(POSTS);
  const author = pickRandom(AUTHORS);

  const payload = {
    language: "it",
    category: "Opinione",
    mood: "Bored",
    author,
    text,
    group_id: "public",
    group_name: "public"
  };

  const { data, error } = await supabase
    .from("posts")
    .insert(payload)
    .select();

  if (error) {
    console.error("Errore inserimento:", error);
    process.exit(1);
  }

  console.log("Post pubblicato:", data);
}

main();
